class Phenotype {
    /**
     * @param {ImageDate} modelData Data of the source image
     * @param {int} nGenotype Number of gene per phenotype
     * @param {Object} genomOptions Look genetic.genomOptions for more information
     */
    constructor(modelData, nGenotype, genomOptions) {
        this.nGenotype = nGenotype;
        this.adn = new Array();
        this.modelData = modelData;
        this.genomOptions = genomOptions;
    }

    /**
     * Generate random ADN
     */
    random() {
        for (let i = 0; i < this.nGenotype; i++) {
            let genotype = new Genotype(this.modelData, this.genomOptions);
            genotype.random();
            this.adn.push(genotype);
        }
    }

    /**
     * Melt two existing ADN
     * @param {Phenotype} father The first descendent of this phenotype
     * @param {Phenotype} mother The second descendent of this phenotype
     */
    inherite(father, mother) {
        for (let i = 0; i < this.nGenotype; i++) {
            let genotype = new Genotype(this.modelData, this.genomOptions);
            if (randBtw(0, 1) == 0) {
                genotype.inherite(father.adn[i])
            } else {
                genotype.inherite(mother.adn[i])
            }
            this.adn.push(genotype);
        }
    }

    /**
     * Show the ADN of this phenotype
     */
    print() {
        console.table(this.adn);
    }

    /**
     * Draw the ADN into a canvas and return his imageData
     * @returns {ImageData} imageData
     */
    pixelData() {
        let canvas = document.createElement('canvas');
        canvas.width = this.modelData.width;
        canvas.height = this.modelData.height;
        let ctx = canvas.getContext('2d');


        ctx.beginPath();
        ctx.rect(0, 0, this.modelData.width, this.modelData.height);
        ctx.fillStyle = "rgb(0, 0, 0)";
        ctx.fill();

        for (const genotype of this.adn) {
            const { x, y, size, color, shape } = genotype;
            ctx.beginPath();
            switch (shape) {
                case 0:
                    ctx.rect(x, y, size, size);
                    break;
                case 1:
                    ctx.arc(x, y, size, 0, 2 * Math.PI);
                    break;
            }
            ctx.fillStyle = `rgb(${color[0]},${color[1]},${color[2]})`;
            ctx.fill();
        }

        return ctx.getImageData(0, 0, this.modelData.width, this.modelData.height).data;
    }

    /**
     * Return a factor between 0 and 100 which show the similarity between the model and the current image generated by this phenotype
     * @returns {int} similarityRatio
     */
    similarity() {
        let imageData = this.pixelData();
        let similarityNumber = 0;
        for (let i = 0; i < imageData.length; i++) {
            if (i % 4 == 3) continue;
            let pixelDifference = Math.abs(imageData[i] - this.modelData.data[i]);
            if (pixelDifference < 30) similarityNumber += (100 - pixelDifference * 3.33)  // Between 0 & 100 %
        }
        this.similarityRatio = similarityNumber / imageData.length * (3 / 4);
        return this.similarityRatio;
    }
}